name: Build & Push image
on:
  push:
    branches: [ master ]
    
permissions:
  contents: read
  packages: write 
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/botanix-labs/bitcoin-prometheus-exporter
    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        id: tag
        run: |
          TAG=$(git rev-parse --short=7 $GITHUB_SHA)
          echo "tag=$TAG" >>"$GITHUB_OUTPUT"

      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t $IMAGE:${{ steps.tag.outputs.tag }} .

      - name: Push image
        run: docker push $IMAGE:${{ steps.tag.outputs.tag }}